adding exit if wrong status

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -51,7 +51,6 @@ jobs:
             "aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{steps.login-aws-ecr.outputs.registry}}",
             ]' --query "Command.CommandId" --output text)
 
-            echo "Command ID: $command_id"
 
             aws ssm wait command-executed \
             --command-id $command_id \
@@ -59,11 +58,11 @@ jobs:
             
             status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
 
-            echo "$status"
-            
             if [ "$status" == "Success" ]; then
               echo "Command executed successfully"
             else
               echo "Command execution failed"
+              echo "Error: $status"
+              exit 1
             fi
 
